---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: network_one

    - name: Launch Nats
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_nats
        image: nats:2.9-linux
        auto_remove: yes
        recreate: yes
        published_ports:
          - 127.0.0.1:4222:4222
          - 127.0.0.1:8222:8222
        network_mode: network_one
        command: -js
        networks:
          - name: network_one
