---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: network_one

    - name: Build image
      community.docker.docker_image:
        name: bitcoin_cashd
        source: build
        build:
          path: .

    - name: Launch 
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_bitcoin_cashd
        image: bitcoin_cashd
        auto_remove: yes
        recreate: yes
        published_ports:
          - 18444:18444  # regtest rpc port
        network_mode: network_one
        networks:
          - name: network_one

    - name: Create test wallet
      community.docker.docker_container_exec:
        container: pgnd_bitcoin_cashd
        command: bitcoin-cli -regtest=1 -rpcuser=test -rpcpassword=test createwallet "test"

    # - name: Generate balance
    #   community.docker.docker_container_exec:
    #     container: pgnd_bitcoin_cashd
    #     command: litecoin-cli -regtest=1 -rpcuser=test -rpcpassword=test -generate 100
