---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: network_one

    - name: Launch Chronograf
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_chronograf
        image: chronograf:1.10-alpine
        auto_remove: yes
        recreate: yes
        published_ports:
          - 127.0.0.1:8888:8888
        network_mode: network_one
        networks:
          - name: network_one
