---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: network_one

    - name: Launch ClickHouse
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_clickhouse
        image: yandex/clickhouse-server:21
        auto_remove: yes
        recreate: yes
        published_ports:
          - 127.0.0.1:9000:9000
        network_mode: network_one
        networks:
          - name: network_one
        env:
          DEBIAN_FRONTEND: noninteractive
