---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Stop ClickHouse"
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_clickhouse
        state: absent
        force_kill: true
