---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "Stop RabbitMQ"
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_rabbitmq
        state: absent
        force_kill: true
