---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Stop Redpanda
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_redpanda
        state: absent
        force_kill: true
