---
- hosts: localhost
  gather_facts: no

  tasks:

    - name: Create a network
      community.docker.docker_network:
        name: network_one

    - name: Launch Scylla
      community.docker.docker_container:
        container_default_behavior: no_defaults
        name: pgnd_scylla
        image: scylladb/scylla:4.6.3
        auto_remove: yes
        recreate: yes
        published_ports:
          - 7000-7001:7000-7001 
          - 9042:9042
          - 9160:9160
          - 9180:9180
          - 10000:10000
        network_mode: network_one
        networks:
          - name: network_one
        command: --smp 1
